GeigerCrowd/Controllers/ReadingPointsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GeigerCrowd.Models;

namespace GeigerCrowd.Controllers
{   
    public class ReadingPointsController : Controller
    {
        private GeigerCrowdContext context = new GeigerCrowdContext();

        //
        // GET: /ReadingPoint/
        [Authorize]
        public ViewResult Index()
        {
            return View(context.ReadingPoints.ToList());
        }

        //
        // GET: /ReadingPoint/Details/5
        [Authorize]
        public ViewResult Details(int id)
        {
			ReadingPoint readingpoint = context.ReadingPoints.Single(x => x.ID == id);
            return View(readingpoint);
        }

        //
        // GET: /ReadingPoint/Create
        [Authorize]
        public ActionResult Create()
        {
            @ViewBag.UserID = this.Request.LogonUserIdentity.User;
            return View();
        } 

        //
        // POST: /ReadingPoint/Create

        [HttpPost]
        [Authorize]
        public ActionResult Create(ReadingPoint readingpoint)
        {
            @ViewBag.UserID = this.Request.LogonUserIdentity.User;
            if (ModelState.IsValid)
            {
				context.ReadingPoints.Add(readingpoint);
				context.SaveChanges();
				return RedirectToAction("Index");  
            }

            return View(readingpoint);
        }
        
        //
        // GET: /ReadingPoint/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            @ViewBag.UserID = this.Request.LogonUserIdentity.User;
			ReadingPoint readingpoint = context.ReadingPoints.Single(x => x.ID == id);
			return View(readingpoint);
        }

        //
        // POST: /ReadingPoint/Edit/5

        [HttpPost]
        [Authorize]
        public ActionResult Edit(ReadingPoint readingpoint)
        {
            if (ModelState.IsValid)
            {
				context.Entry(readingpoint).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(readingpoint);
        }

        //
        // GET: /ReadingPoint/Delete/5

        [Authorize]
        public ActionResult Delete(int id)
        {
			ReadingPoint readingpoint = context.ReadingPoints.Single(x => x.ID == id);
            return View(readingpoint);
        }

        //
        // POST: /ReadingPoint/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            ReadingPoint readingpoint = context.ReadingPoints.Single(x => x.ID == id);
            context.ReadingPoints.Remove(readingpoint);
			context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

GeigerCrowd/Views/Shared/MapLayout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/api.shared.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/api.readingpoints.js")" type="text/javascript"></script>
@RenderSection("Includes")
</head>
 @RenderBody()
</html>

GeigerCrowd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/api.shared.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/api.readingpoints.js")" type="text/javascript"></script>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    @RenderSection("Includes",false)
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Geiger Crowd</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Readings", "Index", "ReadingPoints")</li>
                    <li>@Html.ActionLink("Map", "DefaultMap", "Home")</li>
                </ul>
            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

GeigerCrowd/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Html.ActionLink(@Context.User.Identity.Name,"Profile","Account")</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

GeigerCrowd/Views/Shared/_iframe.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/api.shared.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/api.readingpoints.js")" type="text/javascript"></script>
    @RenderSection("Includes",false)
</head>

<body style="background-color: White;">
@RenderBody()
</body>
</html>